# Урок 4: Работа с модулем NumPy
Добро пожаловать на четвёртый урок по программированию на Python! Сегодня мы познакомимсся с библиотекой **NumPy**.
**NumPy** — это библиотека для языка Python, которая предоставляет удобные и быстрые способы работы с многомерными массивами и матрицами, а также содержит большое количество математических функций для работы с этими массивами. NumPy часто используется в научных вычислениях, анализе данных и машинном обучении.

# 1. Установка NumPy

Для начала работы с NumPy необходимо установить его, если он ещё не установлен. Для этого используйте команду:

In [2]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


### После установки необходимо перезапустить ядро или просто закрыть-открыть VSCode.

# 2. Импорт библиотеки NumPy

После установки можно импортировать NumPy в программу:

In [1]:
import numpy as np

Здесь `np` — это общепринятое сокращение, чтобы не писать длинное `numpy` в каждой строке кода.

# 3. Основные возможности и функции NumPy

## 3.1. Основным объектом NumPy является **многомерный массив** — `ndarray` (n-dimensional array). Он отличается от стандартных списков Python тем, что:

- Все элементы имеют **одинаковый тип данных** (обычно числа).
- Он позволяет выполнять **векторные операции**, то есть операции над всеми элементами массива одновременно, что значительно ускоряет вычисления.
## Пример создания массивов

In [ ]:
import numpy as np

# Одномерный массив (из списка)
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
# Двумерный массив (матрица)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
# Из кортежа
b = np.array((4, 5, 6))
print(b)  # [4 5 6]




## Важные функции для создания массивов:

- **`np.zeros(shape, dtype=float)`**: Создаёт массив, заполненный нулями.

  ```python
  zeros_array = np.zeros((2, 3))
  print(zeros_array)
  # [[0. 0. 0.]
  #  [0. 0. 0.]]
  ```

- **`np.ones(shape, dtype=float)`**: Создаёт массив, заполненный единицами.

  ```python
  ones_array = np.ones((3, 2))
  print(ones_array)
  # [[1. 1.]
  #  [1. 1.]
  #  [1. 1.]]
  ```

- **`np.full(shape, fill_value, dtype=None)`**: Создаёт массив, заполненный заданным значением.

  ```python
  full_array = np.full((2, 2), 7)
  print(full_array)
  # [[7 7]
  #  [7 7]]
  ```

- **`np.eye(N, M=None, k=0, dtype=float)`**: Создаёт единичную матрицу (двумерный массив с единицами на главной диагонали).

  ```python
  identity_matrix = np.eye(3)
  print(identity_matrix)
  # [[1. 0. 0.]
  #  [0. 1. 0.]
  #  [0. 0. 1.]]
  ```

- **`np.arange(start, stop, step, dtype=None)`**: Аналогично встроенной функции `range()`, но возвращает массив.

  ```python
  arr = np.arange(0, 10, 2)
  print(arr)  # [0 2 4 6 8]
  ```

- **`np.linspace(start, stop, num, endpoint=True, retstep=False, dtype=None)`**: Возвращает равномерно распределённые числа на заданном интервале.

  ```python
  linspace_arr = np.linspace(0, 1, 5)
  print(linspace_arr)  # [0.   0.25 0.5  0.75 1.  ]
  ```

### Параметры функций

- **`shape`**: Кортеж или список, определяющий размерность массива.
- **`dtype`**: Тип данных элементов массива (например, `int`, `float`, `complex`).
- **`start`**: Начальное значение последовательности.
- **`stop`**: Конечное значение последовательности (в `arange` не включается, в `linspace` по умолчанию включается).
- **`step`**: Шаг последовательности.
### Пример:

In [ ]:
import numpy as np

zeros_arr = np.zeros((3, 3))  # Массив из нулей 3x3
ones_arr = np.ones((2, 4))    # Массив из единиц 2x4
range_arr = np.arange(0, 10, 2)  # Чётные числа от 0 до 10
linspace_arr = np.linspace(0, 1, 5)  # 5 значений от 0 до 1

print(zeros_arr)
print(ones_arr)
print(range_arr)
print(linspace_arr)

## Типы данных в NumPy

NumPy поддерживает различные типы данных:

- **`int`**: Целые числа (`int8`, `int16`, `int32`, `int64`).
- **`float`**: Числа с плавающей точкой (`float16`, `float32`, `float64`).
- **`complex`**: Комплексные числа (`complex64`, `complex128`).
- **`bool`**: Логический тип данных (`True` или `False`).
- **`string`** и **`unicode`**: Строковые типы данных.

### Задание типа данных

При создании массива можно явно указать тип данных с помощью параметра `dtype`:

In [ ]:
arr = np.array([1, 2, 3], dtype=np.float32)
print(arr.dtype)  # float32

## 3.2. Индексация и срезы

NumPy позволяет легко получать доступ к элементам массива или его частям с помощью индексации и срезов.

### Пример индексации:

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Получение элемента по индексу
print(arr[0])  # 10
print(arr[3])  # 40

### Пример срезов:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Получаем элементы с 2-го по 4-й (индексы 1, 2, 3)
print(arr[1:4])  # [2, 3, 4]

# Получаем элементы с 3-го до конца
print(arr[2:])  # [3, 4, 5, 6, 7]

### Логическая индексация

Можно использовать логические условия для выборки элементов массива.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Выбрать элементы больше 3
condition = arr > 3
print(condition)   # [False False False  True  True]
print(arr[condition])  # [4 5]

## 3.3. Изменение формы массива


### Функция `reshape()`

Метод **`reshape()`** позволяет изменить форму массива без изменения его данных.

```python
arr = np.arange(6)
print(arr)  # [0 1 2 3 4 5]

reshaped_arr = arr.reshape((2, 3))
print(reshaped_arr)
# [[0 1 2]
#  [3 4 5]]
```

### Параметры функции `reshape()`

- **`newshape`**: Новая форма массива, заданная кортежем. Произведение размеров должно совпадать с числом элементов в массиве.

### Пример:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Превращаем одномерный массив в двумерный массив 2x3
reshaped_arr = arr.reshape(2, 3)

print(reshaped_arr)

## 3.4. Математические операции

NumPy поддерживает арифметические операции над массивами поэлементно.


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Сложение массивов
print(arr1 + arr2)  # [5 7 9]

# Умножение массива на число
print(arr1 * 2)  # [2 4 6]

# Возведение массива в степень
print(arr1 ** 2)  # [1 4 9]

### Универсальные функции (ufunc)

NumPy предоставляет большое количество математических функций, применяемых поэлементно.



### Параметры функций

- **`np.sin(x)`**: Синус каждого элемента массива `x`.
- **`np.cos(x)`**: Косинус каждого элемента массива `x`.
- **`np.exp(x)`**: Экспонента каждого элемента массива `x`.
- **`np.sqrt(x)`**: Квадратный корень каждого элемента массива `x`.
- **`np.log(x)`**: Натуральный логарифм каждого элемента массива `x`.

In [ ]:
arr = np.array([0, np.pi / 2, np.pi])

print(np.sin(arr))  # [0.000000e+00 1.000000e+00 1.224646e-16]
print(np.cos(arr))  # [ 1.000000e+00  6.123234e-17 -1.000000e+00]
print(np.exp(arr))  # [ 1.          4.81047738 23.14069263]

## 3.5. Операции с матрицами

NumPy предоставляет функции для выполнения матричных операций.

### Пример умножения матриц:

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Матричное умножение
C = np.dot(A, B)
print(C)

## 3.6. Статистические функции

NumPy содержит много встроенных статистических функций.


### Основные функции

- **`np.min(a, axis=None)`**: Минимальное значение массива `a`.
- **`np.max(a, axis=None)`**: Максимальное значение массива `a`.
- **`np.mean(a, axis=None)`**: Среднее значение элементов массива `a`.
- **`np.median(a, axis=None)`**: Медиана элементов массива `a`.
- **`np.std(a, axis=None)`**: Стандартное отклонение элементов массива `a`.
- **`np.var(a, axis=None)`**: Дисперсия элементов массива `a`.
- **`np.sum(a, axis=None)`**: Сумма элементов массива `a`.



### Параметр `axis`

- **`axis=0`**: Операция выполняется по столбцам.
- **`axis=1`**: Операция выполняется по строкам.
### Пример:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Среднее значение
print(np.mean(arr))  # 3.0

# Стандартное отклонение
print(np.std(arr))  # 1.414

# Максимум и минимум
print(np.max(arr))  # 5
print(np.min(arr))  # 1


arr1 = np.array([[1, 2], [3, 4]])
print(np.sum(arr1, axis=0))  # [4 6]
print(np.sum(arr1, axis=1))  # [3 7]

## 3.7. Генерация случайных чисел


- **`np.random.rand(d0, d1, ..., dn)`**: Генерирует массив заданной формы, заполненный случайными числами из равномерного распределения на интервале [0, 1).

```python
random_arr = np.random.rand(3, 2)
print(random_arr)
```

- **`np.random.randn(d0, d1, ..., dn)`**: Генерирует массив заданной формы, заполненный случайными числами из стандартного нормального распределения.

```python
normal_arr = np.random.randn(3, 3)
print(normal_arr)
```

- **`np.random.randint(low, high=None, size=None, dtype=int)`**: Возвращает случайные целые числа из заданного интервала.

```python
int_arr = np.random.randint(1, 10, size=(2, 2))
print(int_arr)
```

### Параметры функций

- **`low`**: Нижняя граница (включительно).
- **`high`**: Верхняя граница (исключительно).
- **`size`**: Размер выходного массива.
- **`d0, d1, ..., dn`**: Размерности выходного массива.

### Пример:

In [2]:
random_arr = np.random.rand(3, 3)
print(random_arr)

random_int_arr = np.random.randint(1, 10, size=(2, 3))
print(random_int_arr)

normal_arr = np.random.randn(3, 3)
print(normal_arr)

[[0.96378206 0.87177143 0.98229712]
 [0.43556971 0.5656304  0.68631937]
 [0.65288572 0.09160212 0.392808  ]]
[[7 7 2]
 [7 1 7]]
[[-0.01256177 -0.51337175 -0.59110316]
 [ 0.02422629  0.89622877 -0.49134698]
 [-0.38665931 -0.42791214  2.46081699]]


## Линейная алгебра

NumPy содержит модуль `numpy.linalg` для выполнения операций линейной алгебры.


### Основные функции


- **`np.dot(a, b)`**: Матричное умножение массивов `a` и `b`.

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
  
print(np.dot(a, b))
# [[19 22]
#  [43 50]]

- **`np.transpose(a)`** или `a.T`: Транспонирование массива `a`.

In [ ]:
print(a.T)
# [[1 3]
#  [2 4]]

- **`np.linalg.inv(a)`**: Обратная матрица для массива `a`.

In [ ]:
inv_a = np.linalg.inv(a)
print(inv_a)
# [[-2.   1. ]
#  [ 1.5 -0.5]]

- **`np.linalg.det(a)`**: Детерминант массива `a`.

In [ ]:

det_a = np.linalg.det(a)
print(det_a)  # -2.0000000000000004

- **`np.linalg.eig(a)`**: Собственные значения и собственные векторы массива `a`.

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(a)
print("Собственные значения:", eigenvalues)
print("Собственные векторы:", eigenvectors)

#### Параметры функций

- **`a`, `b`**: Входные массивы (матрицы).
- **`axis`**: Ось, по которой выполняется операция.

# 4. Полезные функции и методы

### Функция `np.where(condition, [x, y])`

Возвращает элементы из `x`, где условие `condition` истинно, и элементы из `y` — где ложно.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

result = np.where(arr > 3, arr, 0)
print(result)  # [0 0 0 4 5]

### Функция `np.concatenate((a1, a2, ...), axis=0)`

Объединяет массивы вдоль указанной оси.


In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])

concat_arr = np.concatenate((a, b))
print(concat_arr)  # [1 2 3 4]

### Функция `np.unique(ar, return_counts=False)`

Находит уникальные элементы массива.
Если установить `return_counts=True`, то функция также вернёт количество вхождений каждого элемента.

In [ ]:
arr = np.array([1, 2, 2, 3, 3, 3])

unique_elements = np.unique(arr)
print(unique_elements)  # [1 2 3]

### Функция `np.triu(m,k)`

Функция numpy.triu (Triangle Upper) возвращает верхний треугольник двумерного массива или матрицы. Это означает, что она сохраняет элементы на главной диагонали и выше, а элементы ниже главной диагонали заменяет на нули (или на другое заданное значение).
### Параметры

- **`m`**: Входной массив или матрица, для которой нужно получить верхний треугольник.

- **`k`**: - Диагональ, относительно которой определяется верхний треугольник.
  - По умолчанию `k=0`, что означает главную диагональ.
  - `k > 0`: диагональ выше главной.
  - `k < 0`: диагональ ниже главной.


In [3]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

# Получаем верхний треугольник
upper_triangle = np.triu(a)

print("Оригинальная матрица:")
print(a)

print("\nВерхний треугольник матрицы:")
print(upper_triangle)

Оригинальная матрица:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Верхний треугольник матрицы:
[[ 1  2  3  4]
 [ 0  6  7  8]
 [ 0  0 11 12]
 [ 0  0  0 16]]



- **Документация NumPy**: [https://numpy.org/doc/](https://numpy.org/doc/)

# Задания для закрепления материала

# Задание №1. Нормализация массива с фильтрацией
**Описание**: Создайте массив случайных чисел размером 5x5. Затем отфильтруйте числа, которые больше среднего значения этого массива, и нормализуйте их так, чтобы сумма оставшихся элементов равнялась 1.


In [77]:
import numpy as np

arr = np.random.randint(0,100,size=(5,5))

aver = np.mean(arr)

print('Исходный массив: ')
for i in range(len(arr)):
    print(arr[i])
print(f'Среднее значение массива: {aver}')

filtered_nums = arr[arr > aver]

if len(filtered_nums) > 0:
    filtered_nums = filtered_nums / np.sum(filtered_nums)
else:
    filtered_nums = np.array([])

print(f'Нормализованные элементы:\n {filtered_nums}')
print(f'Сумма нормализованных элементов (проверка): {np.sum(filtered_nums)}')

Исходный массив: 
[89 18  8 66 13]
[39 20 48 87 43]
[11 54  0 54 18]
[79 71 86 40  3]
[40  3  6 91 70]
Среднее значение массива: 42.28
Нормализованные элементы:
 [0.10620525 0.07875895 0.05727924 0.10381862 0.05131265 0.06443914
 0.06443914 0.09427208 0.08472554 0.1026253  0.10859189 0.08353222]
Сумма нормализованных элементов (проверка): 1.0


# Задание №2. Нахождение максимума в каждом ряду
**Описание**: Создайте двумерный массив размером 5x5 с произвольными числами. Пройдитесь по каждому ряду и найдите максимальное значение. Если максимальное значение больше 10, замените все элементы этого ряда на 1.

In [286]:
import numpy as np

arr = np.random.randint(0,20,size=(5,5))
print('Исходный массив: ')
for i in range(len(arr)):
    print(arr[i])

size = len(arr)
max_allowed = 10

for row in range(size):
    if np.max(arr[row]) > max_allowed:
        arr[row,:] = 1
print('Измененный массив:')
for i in range(len(arr)):
    print(arr[i])


Исходный массив: 
[ 5 10  6  9  1]
[ 0  3  8 11 13]
[18  6  3 13  6]
[ 6  9 12  5 15]
[ 5 10  2  0  3]
Измененный массив:
[ 5 10  6  9  1]
[1 1 1 1 1]
[1 1 1 1 1]
[1 1 1 1 1]
[ 5 10  2  0  3]


# Задание №3. Создание симметричной матрицы
**Описание**: Создайте случайную матрицу 4x4 и преобразуйте её в симметричную (где элемент [i, j] равен элементу [j, i]). Если элемент на диагонали меньше 0, замените его на 0.

In [248]:
import numpy as np

arr = np.random.randint(-20,20,size=(4,4))
print('Исходный массив: ')
for i in range(len(arr)):
    print(arr[i])

size = len(arr)

for i in range(size):
    if arr[i,i] < 0:
        arr[i,i] = 0
    for j in range(size):
        if i != j:
            arr[j,i] = arr[i,j]

print('Измененный массив:')
for i in range(len(arr)):
    print(arr[i])

Исходный массив: 
[ -7 -10   0  -9]
[-5 10 -5  8]
[-16 -20   8   2]
[ 18 -10 -14  -5]
Измененный массив:
[  0 -10   0  -9]
[-10  10  -5   8]
[ 0 -5  8  2]
[-9  8  2  0]


# Задание №4. Кумулятивная сумма с проверкой
**Описание**: Создайте массив из 10 случайных чисел. Рассчитайте кумулятивную сумму. Если на каком-либо шаге кумулятивная сумма превышает 50, прекратите вычисления и выведите позицию, на которой произошло превышение.

In [ ]:
import numpy as np

arr = np.random.randint(-10,20,size=(10))
print('Исходный массив: ')
print(arr)
cumsum = 0
maxcumsum = 50
ind = 0
for num in arr:
    cumsum += num
    if cumsum > maxcumsum:
        print(f'Кумулятивная сумма превысила {maxcumsum} на элементе {num} с индексом {ind}')
        break
    ind += 1
    if ind == len(arr):
        print(f'Кумулятивная сумма составила: {cumsum}')



Исходный массив: 
[ 8  6 19  1 12  0 -5 -8 18 -4]
Кумулятивная сумма превысила 50 на элементе 18 с индексом 8


# Задание №5. Создание единичной матрицы с модификацией
**Описание**: Создайте единичную матрицу размером 5x5. Если элемент на главной диагонали является нечётным числом, замените его на 2.

In [247]:
import numpy as np

arr = np.eye(5, 5, dtype=int)
print('Исходный массив: ')
for i in range(len(arr)):
    print(arr[i])
for i in range(len(arr)):
    arr[i,i] = 2
print('Измененный массив:')
for i in range(len(arr)):
    print(arr[i])
    

Исходный массив: 
[1 0 0 0 0]
[0 1 0 0 0]
[0 0 1 0 0]
[0 0 0 1 0]
[0 0 0 0 1]
Измененный массив:
[2 0 0 0 0]
[0 2 0 0 0]
[0 0 2 0 0]
[0 0 0 2 0]
[0 0 0 0 2]


# Задание №6. Матричное умножение с проверкой
**Описание**: Создайте две случайные матрицы 3x3 и выполните их матричное умножение. Если сумма любого столбца в результирующей матрице больше 15, замените все элементы этого столбца на -1.

In [490]:
import numpy as np

arr = np.random.randint(-20,20,size=(3,3))
arr2 = np.random.randint(-20,20,size=(3,3))
print('Исходный первый массив:')
for i in range(len(arr)):
    print(arr[i])
print('Исходный второй массив:')
for i in range(len(arr2)):
    print(arr2[i])

arr_prod = np.dot(arr,arr2)

print('Произведение матриц:')
for i in range(len(arr_prod)):
    print(arr_prod[i])

maxsum = 15
for i in range(len(arr_prod)):
    if np.sum(arr_prod[:,i]) > 15:
        arr_prod[:,i] = -1
print('Измененная матрица:')
for i in range(len(arr_prod)):
    print(arr_prod[i])

Исходный первый массив:
[11 -2 15]
[-10  11 -13]
[-10  -6  10]
Исходный второй массив:
[-16 -15  18]
[-20  13  15]
[-12  16  -1]
Произведение матриц:
[-316   49  153]
[96 85 -2]
[ 160  232 -280]
Измененная матрица:
[-316   -1  153]
[96 -1 -2]
[ 160   -1 -280]


# Задание №7. Нахождение уникальных значений с фильтрацией
**Описание**: Создайте массив случайных чисел. Найдите уникальные элементы. Если количество уникальных элементов больше 10, удалите все числа, которые больше 50.

In [381]:
import numpy as np

arr = np.random.randint(0,20,size=(50))
print(f'Исходный массив:\n{arr}')

uninums = np.unique(arr)
maxuninums = 10
if len(uninums) > maxuninums:
    arr = arr[arr <= maxuninums]

print(f'Новый массив:\n{arr}')

Исходный массив:
[14 18 13 12 10  9  8 10 17 18  5  8 18  3  3  3  1  8 11  5 11  1  1  4
  9  5  3  7 12  2  6 16  8  5  2  9 13 13 11 15  9 11  8  0 12  5 11 17
  6  3]
Новый массив:
[10  9  8 10  5  8  3  3  3  1  8  5  1  1  4  9  5  3  7  2  6  8  5  2
  9  9  8  0  5  6  3]


# Задание №8. Модификация массива на основе медианы
**Описание**: Создайте массив случайных чисел размером 1x10. Найдите медиану массива. Если число больше медианы, умножьте его на 2, если меньше — поделите на 2.

In [414]:
import numpy as np

arr = np.random.randint(0,20,size=(10))
print(f'Исходный массив:\n{arr}')

med = np.median(arr)
print(f'Медиана массива: {med}')
new_arr = []
for num in arr:
    if num > med:
        new_arr.append(int(num*2))
    elif num < med:
        new_arr.append(int(num/2))
    else:
        new_arr.append(int(num))
print(f'Новый массив:\n{new_arr}')

Исходный массив:
[ 9 15 19  2  3  1  7  3  7 14]
Медиана массива: 7.0
Новый массив:
[18, 30, 38, 1, 1, 0, 7, 1, 7, 28]


# Задание №9. Отбор элементов с фильтрацией и умножением
**Описание**: Создайте двумерный массив размером 5x5. Отберите все элементы, которые являются чётными и больше среднего значения массива, и умножьте их на 3.

In [426]:
import numpy as np

arr = np.random.randint(0,20,size=(5,5))
print('Исходный массив:')
for i in range(len(arr)):
    print(arr[i])

aver = np.mean(arr)
print(f'Среднее значение массива: {aver}')
new_arr = []
for i in range(len(arr)):
    for j in range(len(arr)):
        if arr[i,j] % 2 == 0 and arr[i,j] > aver:
            new_arr.append(int(arr[i,j]*3))

print(f'Новый массив:\n{new_arr}')

Исходный массив:
[ 4  2  6 15  7]
[ 2  3 18 13 18]
[10  1 14 18 15]
[16 17 13  5 14]
[17  2 16 10  1]
Среднее значение массива: 10.28
Новый массив:
[54, 54, 42, 54, 48, 42, 48]


# Задание №10. Поэлементное сложение с условиями
**Описание**: Создайте два одномерных массива по 10 элементов каждый. Выполните поэлементное сложение. Если сумма элементов на каком-то шаге превышает 10, замените этот элемент на 0.

In [486]:
import numpy as np

arr = np.random.randint(-20,20,size=(10))
arr2 = np.random.randint(-20,20,size=(10))
print(f'Исходный первый массив:\n{arr}')
print(f'Исходный второй массив:\n{arr2}')
new_arr = []
for i in range(len(arr)):
    summary = arr[i]+arr2[i]
    new_arr.append(int(arr[i]+arr2[i])) if summary <=10 else new_arr.append(0)
print(f'Новый массив:\n{new_arr}')

Исходный первый массив:
[-15  -7 -14 -12 -14  -4   0   4 -12 -16]
Исходный второй массив:
[  6   1  10 -11  -9 -16  17 -13  15   7]
Новый массив:
[-9, -6, -4, -23, -23, -20, 0, -9, 3, -9]


# Задание №11.  Сортировка и фильтрация массива
**Описание**: Создайте массив случайных чисел. Отсортируйте его по возрастанию. Затем найдите все элементы, которые меньше среднего значения массива, и замените их на 0.

In [643]:
import numpy as np

arr = np.random.randint(-50,50,size=(50))
print(f'Исходный массив:\n{arr}')

arr = np.sort(arr)

print(f'Сортированный массив:\n{arr}')

aver = np.mean(arr)
print(f'Среднее значение массива: {aver}')
new_arr = []
for num in arr:
    new_arr.append(int(num)) if num >= aver else new_arr.append(0)
print(f'Фильтрованный массив:\n{new_arr}')


Исходный массив:
[-39 -30  32   4  47  36 -30 -20   3  -2 -50 -10  -6  20 -29 -39 -49 -30
 -21  44  36 -16   4 -31  48  33 -13 -45   8  -3   4 -15  -8 -12  14  -7
  32 -49  43 -34   5   9   7  35 -13 -25 -24 -23  20 -35]
Сортированный массив:
[-50 -49 -49 -45 -39 -39 -35 -34 -31 -30 -30 -30 -29 -25 -24 -23 -21 -20
 -16 -15 -13 -13 -12 -10  -8  -7  -6  -3  -2   3   4   4   4   5   7   8
   9  14  20  20  32  32  33  35  36  36  43  44  47  48]
Среднее значение массива: -4.48
Фильтрованный массив:
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -3, -2, 3, 4, 4, 4, 5, 7, 8, 9, 14, 20, 20, 32, 32, 33, 35, 36, 36, 43, 44, 47, 48]


# Задание №12.  Транспонирование с модификацией
**Описание**: Создайте двумерный массив 3x3. Транспонируйте его и замените все элементы, которые больше 5, на их логарифмы.

In [ ]:
import numpy as np

arr = np.random.randint(0,10,size=(3,3))
print('Исходный массив:')
for i in range(len(arr)):
    print(arr[i])

max_allowed = 5

arr = np.transpose(arr)
print('Транспонированный массив:')
for i in range(len(arr)):
    print(arr[i])

new_arr = np.zeros(dtype = float, shape=(3,3))
for i in range(len(arr)):
    for j in range(len(arr)):
        element = arr[i,j]
        new_arr[i,j]= element if element <= max_allowed else np.log(element)

np.set_printoptions(formatter={'float': '{:0.3f}'.format})

print('Модифицированный массив:')
for i in range(len(new_arr)):
    print(new_arr[i])

Исходный массив:
[1 9 3]
[8 2 6]
[4 5 1]
Транспонированный массив:
[1 8 4]
[9 2 5]
[3 6 1]
Модифицированный массив:
[1.000 2.079 4.000]
[2.197 2.000 5.000]
[3.000 1.792 1.000]


# Задание №13.  Обратная матрица с проверкой
**Описание**: Создайте случайную матрицу 3x3. Найдите её обратную матрицу. Если сумма какого-либо ряда в обратной матрице больше 10, умножьте этот ряд на 2.

In [626]:
import numpy as np

arr = np.random.randint(1,20,size=(3,3))
print('Исходная матрица:')
for i in range(len(arr)):
    print(arr[i])

max_allowed = 10

arr = np.linalg.inv(arr)
print('Обратная матрица:')
for i in range(len(arr)):
    print(arr[i])

new_arr = np.zeros(dtype = float, shape=(3,3))
for i in range(len(arr)):
    new_arr[i,:]= arr[i,:] if np.sum(arr[i,:]) <= max_allowed else arr[i,:]*2

np.set_printoptions(formatter={'float': '{:0.3f}'.format})

print('Модифицированная матрица:')
for i in range(len(new_arr)):
    print(new_arr[i])


Исходная матрица:
[19  8 10]
[17  8 10]
[ 1 16  1]
Обратная матрица:
[0.500 -0.500 0.000]
[0.023 -0.030 0.066]
[-0.868 0.974 -0.053]
Модифицированная матрица:
[0.500 -0.500 0.000]
[0.023 -0.030 0.066]
[-0.868 0.974 -0.053]


# Задание №14. Перемешивание с модификацией
**Описание**: Создайте массив из 10 чисел. Перемешайте элементы массива случайным образом. Если в новом массиве есть числа больше 5, уменьшите их на 3.

In [647]:
import numpy as np

arr = np.random.randint(-50,50,size=(10))
print(f'Исходный массив:\n{arr}')

np.random.shuffle(arr)
print(f'Перемешанный массив:\n{arr}')

max_allowed = 5
new_arr = []

for num in arr:
    new_arr.append(int(num)) if num <= max_allowed else new_arr.append(int(num-3))

print(f'Модифицированный массив:\n{new_arr}')

Исходный массив:
[ 18  26  11  44   4  31  32  42 -23  34]
Перемешанный массив:
[  4  18  11 -23  26  31  42  32  34  44]
Модифицированный массив:
[4, 15, 8, -23, 23, 28, 39, 29, 31, 41]


# Задание №15.  Цикл с вложенным условием
**Описание**: Создайте двумерный массив 4x4. Для каждого элемента массива выполните следующее: если элемент чётный, возведите его в квадрат, если нечётный — умножьте на 2.

In [650]:
import numpy as np

arr = np.random.randint(1,20,size=(3,3))
print('Исходная матрица:')
for i in range(len(arr)):
    print(arr[i])

new_arr = arr

for i in range(len(arr)):
    for j in range(len(arr)):
        new_arr[i,j] = 2*arr[i,j] if (arr[i,j] % 2) else arr[i,j]**2
print('Модифицированный массив:')
for i in range(len(new_arr)):
    print(new_arr[i])

Исходная матрица:
[8 4 1]
[15  5 17]
[ 6 15 11]
Модифицированный массив:
[64 16  2]
[30 10 34]
[36 30 22]
